// One icon language for every non-brand interface glyph in the app.
// Component aliases keep call sites readable while Phosphor owns rendering.
export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDown,
  DownloadSimple as ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  BellRinging as BellDot,
  Brain,
  Briefcase as BriefcaseBusiness,
  CalendarBlank as CalendarClock,
  Check,
  CheckCircle,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  Circle,
  Clock as Clock3,
  ClipboardText as ClipboardCopy,
  Copy,
  EyeSlash as EyeOff,
  ArrowSquareOut as ExternalLink,
  FolderPlus,
  Gauge,
  Globe as Globe2,
  SpinnerGap as Loader2,
  MagnifyingGlass as Search,
  Microphone as Mic,
  Monitor,
  Moon,
  PencilSimple as Pencil,
  PushPin as Pin,
  PushPinSlash as PinOff,
  Play,
  Plus,
  Power,
  PuzzlePiece as Puzzle,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  Gear as Settings,
  ShieldCheck,
  UploadSimple as Upload,
  Sparkle as Sparkles,
  Square,
  Trash as Trash2,
  UsersThree as Users,
  WarningCircle,
  X,
} from "@phosphor-icons/react";
